services:
  server:
    image: anhvietanh1123/ai-study-hub-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DB_NAME: ${DB_NAME}
      BASE_URL: ${BASE_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - '5285:5285'
    volumes:
      - uploads-data:/usr/src/app/uploads
    restart: unless-stopped

volumes:
  uploads-data:
