export const ACCOUNT_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  //name
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Name length must be from 1 to 100',
  //email
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  //password
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'Password length must be from 8 to 50',
  PASSWORD_MUST_BE_STRONG:
    'Password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  //confirmPassword
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'Confirm length must be from 8 to 50',
  CONFIRM_PASSWORD_MUST_BE_STRONG:
    'Confirm password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_MUST_BE_THE_SAME_AS_PASSWORD: 'Confirm password must be the same as password',
  //dateOfBirth
  DATE_OF_BIRTH_BE_ISO8601: 'Date of birth must be ISO8601',
  //user
  EMAIL_OR_PASSWORD_IS_INCORRECT: 'Email or password is incorrect',
  LOGIN_SUCCESS: 'Login is success',
  ACCESS_TOKEN_IS_REQUIRED: 'Access Token is Required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh Token is Required',
  REFRESH_TOKEN_IS_INVALID: 'Refresh Token is invalid',
  LOGOUT_SUCCESS: 'Logout success',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email already verified before',
  EMAIL_HAS_BEEN_VERIFIED: 'Email has been verified',
  EMAIL_VERIFY_SUCCESS: 'Email verify success',
  EMAIL_VERIFY_TOKEN_IS_VALID: 'Email verify token is valid',
  EMAIL_VERIFY_TOKEN_IS_INVALID: 'Email verify token is invalid',
  EMAIL_HAS_BEEN_BANNED: 'Email has been banned',
  CHECK_YOUR_EMAIL: 'Check your email',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password is required',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Forgot password token is invalid',
  RESET_PASSWORD_SUCCESS: 'Reset password is success',
  VERIFY_FORGOT_PASSWORD_TOKEN_SUCESS: 'Verfiy forgot password token success',
  RESET_PASSWORD_EMAIL_SENT: 'Reset password email has been sent if the account exists',
  GET_ME_SUCCESS: 'Get user infor success',
  BIO_MUST_BE_A_STRING: 'Bio must be a string',
  BIO_LENGTH_MUST_BE_LESS_THAN_200: 'Bio length must be less than 200',
  LOCATION_MUST_BE_A_STRING: 'Location must be a string',
  LOCATION_LENGTH_MUST_BE_LESS_THAN_200: 'Location length must be less than 200',
  WEBSITE_MUST_BE_A_STRING: 'Website must be a string',
  WEBSITE_LENGTH_MUST_BE_LESS_THAN_200: 'Website length must be less than 200',
  USERNAME_MUST_BE_A_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_LESS_THAN_50: 'Username length must be less than 50',
  IMAGE_URL_MUST_BE_A_STRING: 'Image url must be a string',
  IMAGE_URL_LENGTH_MUST_BE_LESS_THAN_400: 'Image url length must be less than 400',
  UPDATE_PROFILE_SUCCESS: 'Update profile success',
  USER_NOT_VERIFIED: 'User not verified',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  USERNAME_IS_INVALID: 'Username is invalid',
  IMAGE_URL_LENGTH_MUST_BE_FROM_1_TO_400: 'Image url length must be from 1 to 400',
  YOU_MUST_VERIFY_YOUR_EMAIL_TO_UPDATE_PROFILE: 'You must verify your email to update profile',
  CHANGE_PASSWORD_SUCCESS: 'Change passwprd success',
  REFRESH_TOKEN_SUCCESS: 'Refresh token reset success',
  UPLOAD_IMAGE_SUCCESS: 'Upload image success',
  UPLOAD_VIDEO_SUCCESS: 'Upload video success',
  USER_BANNED_CANNOT_RESEND_VERIFY_EMAIL: 'User banned cannot resend verify email',

  REGISTER_SUCCESS: 'Register success',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Verification email has been resent',
  //otp
  OTP_IS_REQUIRED: 'OTP is required',
  OTP_MUST_BE_6_DIGITS: 'OTP must be 6 digits',
  OTP_IS_INVALID_OR_EXPIRED: 'OTP is invalid or expired',
  ACCESS_TOKEN_IS_INVALID: 'Access token is invalid',
  AUTHORIZATION_HEADER_IS_INVALID: 'Authorization header is invalid'
} as const

export const USER_MESSAGES = {
  USER_NOT_FOUND: 'User not found',
  USER_IS_INACTIVE: 'User is inactive',
  USER_NOT_VERIFIED: 'User not verified',
  GET_PROFILE_SUCCESS: 'Get profile success',
  GET_STORAGE_SUCCESS: 'Get storage success',
  FULL_NAME_MUST_BE_A_STRING: 'Full name must be a string',
  FULL_NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Full name length must be from 1 to 100',
  USERNAME_MUST_BE_A_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Username length must be from 1 to 100',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  AVATAR_FILE_TOO_LARGE: 'Avatar file must be less than or equal to 2MB',
  AVATAR_FILE_TYPE_IS_INVALID: 'Avatar file must be a jpg, jpeg, or png image',
  UPDATE_PROFILE_SUCCESS: 'Update profile success',
  CURRENT_PASSWORD_IS_REQUIRED: 'Current password is required',
  CURRENT_PASSWORD_MUST_BE_A_STRING: 'Current password must be a string',
  CURRENT_PASSWORD_IS_INCORRECT: 'Current password is incorrect',
  NEW_PASSWORD_IS_REQUIRED: 'New password is required',
  NEW_PASSWORD_MUST_BE_A_STRING: 'New password must be a string',
  NEW_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'New password length must be from 8 to 50',
  NEW_PASSWORD_MUST_BE_STRONG:
    'New password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'Confirm password length must be from 8 to 50',
  CONFIRM_PASSWORD_MUST_BE_STRONG:
    'Confirm password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_MUST_BE_THE_SAME_AS_NEW_PASSWORD: 'Confirm password must be the same as new password',
  CHANGE_PASSWORD_SUCCESS: 'Change password success'
} as const

export const DOCUMENT_MESSAGES = {
  FILE_IS_REQUIRED: 'Document file is required',
  FILE_TOO_LARGE: 'Document file exceeds storage plan limit',
  FILE_TYPE_IS_INVALID: 'Document file must be a pdf, docx, or txt file',
  STORAGE_QUOTA_EXCEEDED: 'Storage quota exceeded',
  TITLE_IS_REQUIRED: 'Title is required',
  TITLE_MUST_BE_A_STRING: 'Title must be a string',
  TITLE_LENGTH_MUST_BE_FROM_1_TO_200: 'Title length must be from 1 to 200',
  DESCRIPTION_MUST_BE_A_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH_MUST_BE_LESS_THAN_1000: 'Description length must be less than 1000',
  CATEGORY_ID_IS_INVALID: 'Category id is invalid',
  CATEGORY_NOT_FOUND: 'Category not found',
  TAGS_MUST_BE_AN_ARRAY_OR_STRING: 'Tags must be an array or comma separated string',
  LANGUAGE_MUST_BE_A_STRING: 'Language must be a string',
  LANGUAGE_LENGTH_MUST_BE_FROM_2_TO_20: 'Language length must be from 2 to 20',
  IS_PUBLIC_MUST_BE_BOOLEAN: 'isPublic must be a boolean',
  AI_STATUS_IS_INVALID: 'AI status is invalid',
  SORT_BY_IS_INVALID: 'Sort by is invalid',
  ORDER_IS_INVALID: 'Order is invalid',
  PAGE_MUST_BE_A_POSITIVE_INTEGER: 'Page must be a positive integer',
  LIMIT_MUST_BE_FROM_1_TO_100: 'Limit must be from 1 to 100',
  DOCUMENT_ID_IS_INVALID: 'Document id is invalid',
  DOCUMENT_NOT_FOUND: 'Document not found',
  DOCUMENT_ACCESS_DENIED: 'You do not have permission to access this document',
  DOCUMENT_UPDATE_DENIED: 'Only the owner can update this document',
  DOCUMENT_DELETE_DENIED: 'Only the owner can delete this document',
  DOCUMENT_ALREADY_DELETED: 'Document already deleted',
  DOCUMENT_FILE_NOT_FOUND: 'Document file not found',
  UPLOAD_DOCUMENT_SUCCESS: 'Document upload success',
  GET_DOCUMENTS_SUCCESS: 'Get documents success',
  GET_DOCUMENT_DETAIL_SUCCESS: 'Get document detail success',
  GET_UPLOAD_STATUS_SUCCESS: 'Get upload status success',
  DOWNLOAD_DOCUMENT_SUCCESS: 'Download document success',
  UPDATE_DOCUMENT_SUCCESS: 'Update document success',
  DELETE_DOCUMENT_SUCCESS: 'Delete document success'
} as const

export const FOLDER_MESSAGES = {
  FOLDER_NAME_IS_REQUIRED: 'Folder name is required',
  FOLDER_NAME_MUST_BE_A_STRING: 'Folder name must be a string',
  FOLDER_NAME_LENGTH_MUST_BE_FROM_1_TO_120: 'Folder name length must be from 1 to 120',
  FOLDER_SEARCH_LENGTH_MUST_BE_LESS_THAN_200: 'Folder search length must be less than 200',
  FOLDER_ID_IS_INVALID: 'Folder id is invalid',
  PARENT_FOLDER_ID_IS_INVALID: 'Parent folder id is invalid',
  SORT_BY_IS_INVALID: 'Folder sort by is invalid',
  ORDER_IS_INVALID: 'Folder order is invalid',
  DELETE_CONFIRMATION_IS_REQUIRED: 'Cascade delete confirmation is required',
  FOLDER_NOT_FOUND: 'Folder not found',
  FOLDER_ACCESS_DENIED: 'You do not have permission to access this folder',
  FOLDER_CREATE_SUCCESS: 'Create folder success',
  FOLDER_LIST_SUCCESS: 'Get folder contents success',
  FOLDER_DETAIL_SUCCESS: 'Get folder detail success',
  FOLDER_UPDATE_SUCCESS: 'Update folder success',
  FOLDER_MOVE_SUCCESS: 'Move folder success',
  FOLDER_DELETE_SUCCESS: 'Delete folder success',
  FOLDER_DELETE_DENIED: 'Only the owner can delete this folder',
  FOLDER_ALREADY_DELETED: 'Folder already deleted',
  CANNOT_MOVE_FOLDER_TO_ITSELF: 'Cannot move folder into itself',
  CANNOT_MOVE_FOLDER_TO_DESCENDANT: 'Cannot move folder into one of its descendants',
  PARENT_FOLDER_NOT_FOUND: 'Parent folder not found',
  CASCADE_DELETE_FOLDER_SUCCESS: 'Cascade delete folder success'
} as const

export const BOOKMARK_MESSAGES = {
  NOTE_MUST_BE_A_STRING: 'Bookmark note must be a string',
  NOTE_LENGTH_MUST_BE_LESS_THAN_300: 'Bookmark note length must be less than 300',
  PAGE_MUST_BE_A_POSITIVE_INTEGER: 'Page must be a positive integer',
  LIMIT_MUST_BE_FROM_1_TO_100: 'Limit must be from 1 to 100',
  BOOKMARK_NOT_FOUND: 'Bookmark not found',
  ADD_BOOKMARK_SUCCESS: 'Add bookmark success',
  REMOVE_BOOKMARK_SUCCESS: 'Remove bookmark success',
  GET_BOOKMARKS_SUCCESS: 'Get bookmarks success'
} as const

export const SHARING_MESSAGES = {
  SHARE_ID_IS_INVALID: 'Share id is invalid',
  SHARE_TOKEN_IS_REQUIRED: 'Share token is required',
  SHARE_TOKEN_MUST_BE_A_STRING: 'Share token must be a string',
  SHARE_TOKEN_LENGTH_MUST_BE_LESS_THAN_200: 'Share token length must be less than 200',
  PERMISSION_LEVEL_IS_REQUIRED: 'Permission level is required',
  PERMISSION_LEVEL_IS_INVALID: 'Permission level is invalid',
  CAN_DOWNLOAD_MUST_BE_BOOLEAN: 'canDownload must be a boolean',
  CAN_COMMENT_MUST_BE_BOOLEAN: 'canComment must be a boolean',
  REQUIRES_LOGIN_MUST_BE_BOOLEAN: 'requiresLogin must be a boolean',
  PASSWORD_HASH_MUST_BE_A_STRING: 'passwordHash must be a string',
  PASSWORD_HASH_LENGTH_MUST_BE_LESS_THAN_200: 'passwordHash length must be less than 200',
  MAX_USES_MUST_BE_A_POSITIVE_INTEGER: 'maxUses must be a positive integer',
  EXPIRES_IN_DAYS_MUST_BE_A_NON_NEGATIVE_INTEGER: 'expiresInDays must be a non-negative integer',
  NOTE_MUST_BE_A_STRING: 'Share note must be a string',
  NOTE_LENGTH_MUST_BE_LESS_THAN_300: 'Share note length must be less than 300',
  SHARE_LINK_OWNER_REQUIRED: 'Only the document owner can manage share links',
  SHARE_LINK_NOT_FOUND: 'Share link not found',
  SHARE_LINK_EXPIRED: 'Share link expired',
  SHARE_LINK_USAGE_LIMIT_REACHED: 'Share link usage limit reached',
  SHARE_TOKEN_GENERATION_FAILED: 'Could not generate share token',
  CREATE_SHARE_LINK_SUCCESS: 'Create share link success',
  GET_SHARE_LINKS_SUCCESS: 'Get share links success',
  REVOKE_SHARE_LINK_SUCCESS: 'Revoke share link success',
  GET_SHARED_DOCUMENT_SUCCESS: 'Get shared document success'
} as const

export const ADMIN_MESSAGES = {
  ADMIN_ROLE_REQUIRED: 'Admin role is required',
  ADMIN_NOT_FOUND: 'Admin account not found',
  ADMIN_IS_INACTIVE: 'Admin account is inactive',
  ADMIN_NOT_VERIFIED: 'Admin account is not verified',
  CANNOT_MODIFY_LAST_ADMIN: 'Cannot modify the last active admin account',
  CANNOT_MODIFY_SELF: 'Admin cannot perform this action on themself',
  GET_USERS_SUCCESS: 'Get admin users success',
  GET_USER_DETAIL_SUCCESS: 'Get admin user detail success',
  UPDATE_USER_STATUS_SUCCESS: 'Update user status success',
  UPDATE_USER_ROLE_SUCCESS: 'Update user role success',
  UPDATE_USER_STORAGE_QUOTA_SUCCESS: 'Update user storage quota success',
  DELETE_USER_SUCCESS: 'Delete user success',
  GET_ADMIN_DOCUMENTS_SUCCESS: 'Get admin documents success',
  DELETE_ADMIN_DOCUMENT_SUCCESS: 'Admin delete document success',
  FLAG_DOCUMENT_SUCCESS: 'Flag document success',
  GET_DASHBOARD_SUCCESS: 'Get dashboard success',
  GET_USER_STATS_SUCCESS: 'Get user statistics success',
  GET_DOCUMENT_STATS_SUCCESS: 'Get document statistics success',
  USER_ID_IS_INVALID: 'User id is invalid',
  ROLE_IS_INVALID: 'Role is invalid',
  STATUS_IS_INVALID: 'Status is invalid',
  STORAGE_PLAN_IS_INVALID: 'Storage plan is invalid',
  REASON_IS_REQUIRED: 'Reason is required',
  REASON_MUST_BE_A_STRING: 'Reason must be a string',
  IS_ACTIVE_MUST_BE_BOOLEAN: 'isActive must be a boolean',
  TOTAL_BYTES_MUST_BE_A_NON_NEGATIVE_INTEGER: 'totalBytes must be a non-negative integer',
  MAX_FILE_SIZE_BYTES_MUST_BE_A_NON_NEGATIVE_INTEGER: 'maxFileSizeBytes must be a non-negative integer',
  AI_QUERIES_LIMIT_MUST_BE_AN_INTEGER: 'aiQueriesLimit must be an integer',
  PERIOD_IS_INVALID: 'Period is invalid',
  GROUP_BY_IS_INVALID: 'groupBy is invalid',
  DATE_IS_INVALID: 'Date must be ISO8601',
  FLAG_CATEGORY_IS_INVALID: 'Flag category is invalid',
  FLAGGED_MUST_BE_BOOLEAN: 'flagged must be a boolean',
  NOTIFY_USER_MUST_BE_BOOLEAN: 'notifyUser must be a boolean'
} as const

export const CATEGORY_MESSAGES = {
  GET_CATEGORIES_SUCCESS: 'Get categories success',
  CREATE_CATEGORY_SUCCESS: 'Create category success',
  UPDATE_CATEGORY_SUCCESS: 'Update category success',
  DELETE_CATEGORY_SUCCESS: 'Delete category success',
  CATEGORY_NOT_FOUND: 'Category not found',
  CATEGORY_ALREADY_EXISTS: 'Category name or slug already exists',
  CATEGORY_IS_IN_USE: 'Category is in use. Provide migrateTo to move documents before deleting',
  CANNOT_MIGRATE_TO_SAME_CATEGORY: 'Cannot migrate documents to the same category',
  NAME_IS_REQUIRED: 'Category name is required',
  NAME_MUST_BE_A_STRING: 'Category name must be a string',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Category name length must be from 1 to 100',
  SLUG_IS_REQUIRED: 'Category slug is required',
  SLUG_MUST_BE_A_STRING: 'Category slug must be a string',
  SLUG_IS_INVALID: 'Category slug is invalid',
  DESCRIPTION_MUST_BE_A_STRING: 'Description must be a string',
  ICON_MUST_BE_A_STRING: 'Icon must be a string',
  COLOR_IS_INVALID: 'Color must be a hex color',
  TYPE_IS_INVALID: 'Category type is invalid',
  ACCEPTED_EXTENSIONS_MUST_BE_AN_ARRAY: 'acceptedExtensions must be an array of strings',
  SORT_ORDER_MUST_BE_AN_INTEGER: 'sortOrder must be an integer',
  PARENT_ID_IS_INVALID: 'Parent id is invalid',
  CATEGORY_ID_IS_INVALID: 'Category id is invalid',
  IS_ACTIVE_MUST_BE_BOOLEAN: 'isActive must be a boolean'
} as const

export const NOTIFICATION_MESSAGES = {
  SEND_NOTIFICATION_SUCCESS: 'Send notification success',
  GET_ADMIN_NOTIFICATIONS_SUCCESS: 'Get admin notifications success',
  GET_NOTIFICATIONS_SUCCESS: 'Get notifications success',
  MARK_NOTIFICATION_READ_SUCCESS: 'Mark notification read success',
  NOTIFICATION_NOT_FOUND: 'Notification not found',
  TITLE_IS_REQUIRED: 'Notification title is required',
  TITLE_MUST_BE_A_STRING: 'Notification title must be a string',
  TITLE_LENGTH_MUST_BE_FROM_1_TO_300: 'Notification title length must be from 1 to 300',
  BODY_IS_REQUIRED: 'Notification body is required',
  BODY_MUST_BE_A_STRING: 'Notification body must be a string',
  TYPE_IS_INVALID: 'Notification type is invalid',
  PRIORITY_IS_INVALID: 'Notification priority is invalid',
  TARGET_IS_INVALID: 'Notification target is invalid',
  RECIPIENT_IDS_ARE_REQUIRED: 'recipientIds are required when target is recipientIds',
  RECIPIENT_IDS_MUST_BE_AN_ARRAY: 'recipientIds must be an array of ObjectId strings',
  RECIPIENT_NOT_FOUND: 'One or more recipients were not found',
  REF_ENTITY_IS_INVALID: 'refEntity is invalid',
  REF_ENTITY_ID_IS_INVALID: 'refEntityId is invalid',
  ACTION_URL_MUST_BE_A_STRING: 'actionUrl must be a string',
  SEND_EMAIL_MUST_BE_BOOLEAN: 'sendEmail must be a boolean',
  IS_READ_MUST_BE_BOOLEAN: 'isRead must be a boolean',
  NOTIFICATION_ID_IS_INVALID: 'Notification id is invalid'
} as const
