export const ACCOUNT_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  //name
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Name length must be from 1 to 100',
  //email
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  //password
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'Password length must be from 8 to 50',
  PASSWORD_MUST_BE_STRONG:
    'Password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  //confirmPassword
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'Confirm length must be from 8 to 50',
  CONFIRM_PASSWORD_MUST_BE_STRONG:
    'Confirm password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_MUST_BE_THE_SAME_AS_PASSWORD: 'Confirm password must be the same as password',
  //dateOfBirth
  DATE_OF_BIRTH_BE_ISO8601: 'Date of birth must be ISO8601',
  //user
  EMAIL_OR_PASSWORD_IS_INCORRECT: 'Email or password is incorrect',
  LOGIN_SUCCESS: 'Login is success',
  ACCESS_TOKEN_IS_REQUIRED: 'Access Token is Required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh Token is Required',
  REFRESH_TOKEN_IS_INVALID: 'Refresh Token is invalid',
  LOGOUT_SUCCESS: 'Logout success',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_VERIFIED_BEFORE: 'Email already verified before',
  EMAIL_HAS_BEEN_VERIFIED: 'Email has been verified',
  EMAIL_VERIFY_SUCCESS: 'Email verify success',
  EMAIL_VERIFY_TOKEN_IS_VALID: 'Email verify token is valid',
  EMAIL_VERIFY_TOKEN_IS_INVALID: 'Email verify token is invalid',
  EMAIL_HAS_BEEN_BANNED: 'Email has been banned',
  CHECK_YOUR_EMAIL: 'Check your email',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password is required',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Forgot password token is invalid',
  RESET_PASSWORD_SUCCESS: 'Reset password is success',
  VERIFY_FORGOT_PASSWORD_TOKEN_SUCESS: 'Verfiy forgot password token success',
  RESET_PASSWORD_EMAIL_SENT: 'Reset password email has been sent if the account exists',
  GET_ME_SUCCESS: 'Get user infor success',
  BIO_MUST_BE_A_STRING: 'Bio must be a string',
  BIO_LENGTH_MUST_BE_LESS_THAN_200: 'Bio length must be less than 200',
  LOCATION_MUST_BE_A_STRING: 'Location must be a string',
  LOCATION_LENGTH_MUST_BE_LESS_THAN_200: 'Location length must be less than 200',
  WEBSITE_MUST_BE_A_STRING: 'Website must be a string',
  WEBSITE_LENGTH_MUST_BE_LESS_THAN_200: 'Website length must be less than 200',
  USERNAME_MUST_BE_A_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_LESS_THAN_50: 'Username length must be less than 50',
  IMAGE_URL_MUST_BE_A_STRING: 'Image url must be a string',
  IMAGE_URL_LENGTH_MUST_BE_LESS_THAN_400: 'Image url length must be less than 400',
  UPDATE_PROFILE_SUCCESS: 'Update profile success',
  USER_NOT_VERIFIED: 'User not verified',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  USERNAME_IS_INVALID: 'Username is invalid',
  IMAGE_URL_LENGTH_MUST_BE_FROM_1_TO_400: 'Image url length must be from 1 to 400',
  YOU_MUST_VERIFY_YOUR_EMAIL_TO_UPDATE_PROFILE: 'You must verify your email to update profile',
  CHANGE_PASSWORD_SUCCESS: 'Change passwprd success',
  REFRESH_TOKEN_SUCCESS: 'Refresh token reset success',
  UPLOAD_IMAGE_SUCCESS: 'Upload image success',
  UPLOAD_VIDEO_SUCCESS: 'Upload video success',
  USER_BANNED_CANNOT_RESEND_VERIFY_EMAIL: 'User banned cannot resend verify email',

  REGISTER_SUCCESS: 'Register success',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Verification email has been resent',
  ACCESS_TOKEN_IS_INVALID: 'Access token is invalid',
  AUTHORIZATION_HEADER_IS_INVALID: 'Authorization header is invalid'
} as const

export const USER_MESSAGES = {
  USER_NOT_FOUND: 'User not found',
  USER_IS_INACTIVE: 'User is inactive',
  USER_NOT_VERIFIED: 'User not verified',
  FULL_NAME_MUST_BE_A_STRING: 'Full name must be a string',
  FULL_NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Full name length must be from 1 to 100',
  USERNAME_MUST_BE_A_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Username length must be from 1 to 100',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  AVATAR_FILE_TOO_LARGE: 'Avatar file must be less than or equal to 2MB',
  AVATAR_FILE_TYPE_IS_INVALID: 'Avatar file must be a jpg, jpeg, or png image',
  UPDATE_PROFILE_SUCCESS: 'Update profile success',
  CURRENT_PASSWORD_IS_REQUIRED: 'Current password is required',
  CURRENT_PASSWORD_MUST_BE_A_STRING: 'Current password must be a string',
  CURRENT_PASSWORD_IS_INCORRECT: 'Current password is incorrect',
  NEW_PASSWORD_IS_REQUIRED: 'New password is required',
  NEW_PASSWORD_MUST_BE_A_STRING: 'New password must be a string',
  NEW_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'New password length must be from 8 to 50',
  NEW_PASSWORD_MUST_BE_STRONG:
    'New password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_50: 'Confirm password length must be from 8 to 50',
  CONFIRM_PASSWORD_MUST_BE_STRONG:
    'Confirm password must be at least 8 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_MUST_BE_THE_SAME_AS_NEW_PASSWORD: 'Confirm password must be the same as new password',
  CHANGE_PASSWORD_SUCCESS: 'Change password success'
} as const

export const DOCUMENT_MESSAGES = {
  FILE_IS_REQUIRED: 'Document file is required',
  FILE_TOO_LARGE: 'Document file exceeds storage plan limit',
  FILE_TYPE_IS_INVALID: 'Document file must be a pdf, docx, or txt file',
  STORAGE_QUOTA_EXCEEDED: 'Storage quota exceeded',
  TITLE_IS_REQUIRED: 'Title is required',
  TITLE_MUST_BE_A_STRING: 'Title must be a string',
  TITLE_LENGTH_MUST_BE_FROM_1_TO_200: 'Title length must be from 1 to 200',
  DESCRIPTION_MUST_BE_A_STRING: 'Description must be a string',
  DESCRIPTION_LENGTH_MUST_BE_LESS_THAN_1000: 'Description length must be less than 1000',
  CATEGORY_ID_IS_INVALID: 'Category id is invalid',
  CATEGORY_NOT_FOUND: 'Category not found',
  TAGS_MUST_BE_AN_ARRAY_OR_STRING: 'Tags must be an array or comma separated string',
  LANGUAGE_MUST_BE_A_STRING: 'Language must be a string',
  LANGUAGE_LENGTH_MUST_BE_FROM_2_TO_20: 'Language length must be from 2 to 20',
  IS_PUBLIC_MUST_BE_BOOLEAN: 'isPublic must be a boolean',
  ENABLE_OCR_MUST_BE_BOOLEAN: 'enableOcr must be a boolean',
  AI_STATUS_IS_INVALID: 'AI status is invalid',
  SORT_BY_IS_INVALID: 'Sort by is invalid',
  ORDER_IS_INVALID: 'Order is invalid',
  PAGE_MUST_BE_A_POSITIVE_INTEGER: 'Page must be a positive integer',
  LIMIT_MUST_BE_FROM_1_TO_100: 'Limit must be from 1 to 100',
  DOCUMENT_ID_IS_INVALID: 'Document id is invalid',
  DOCUMENT_NOT_FOUND: 'Document not found',
  DOCUMENT_ACCESS_DENIED: 'You do not have permission to access this document',
  DOCUMENT_UPDATE_DENIED: 'Only the owner can update this document',
  UPLOAD_DOCUMENT_SUCCESS: 'Document upload success',
  GET_DOCUMENTS_SUCCESS: 'Get documents success',
  GET_DOCUMENT_DETAIL_SUCCESS: 'Get document detail success',
  UPDATE_DOCUMENT_SUCCESS: 'Update document success'
} as const
